[package]
name = "hitc"
version = "0.1.0"
edition = "2021"
default-run = "compiler"

[lib]
name = "compiler"
path = "src/lib.rs"

[[bin]]
name = "compiler"
path = "src/main.rs"

[[bin]]
name = "compiler-clang"
path = "src/main_clang.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clang = "2.0.0"
# 使用clap 稳定版
clap = "3.0.0-beta.2"
lazy_static = "1.4.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_yaml = "0.9.30"
thiserror = "1.0.50"
typed-arena = "2.0.2"
once_cell = "1.7.2"

# 特性管理
[features]
# default = ["clang_frontend"]
clang_frontend = []
